### ISSUE TITLE
Extension froze settings with custom values for speed

### ISSUE THREAD

**Issue by krystian3w** [Dosx001/YouTubeUtils#1]
If I froce my 1.7 speed by DevTools then rest of settings are frozen untill I back to allowed speed e.g. 1.75.

**Comment by Dosx001** [comment]
Can you be more descriptive? How in the DevTools are you changing the playback speed? Could some screenshots help?

**Comment by krystian3w** [comment]
I copy moz-extension URL with UUID and I override 1.75 to 1.7 at `[value=]` in HTML.

> `view-source:moz-extension://UUID/popup/index.html` (I removing `view-source:`)

Maybe possible copy with credits "progress" bar from: https://github.com/WaldiPL/playbackSpeed to support more values without hacks.

**Comment by Dosx001** [comment]
I still don't see the problem/bug but I can add an input range for playback speed. I'll work on it later in the week.

**Comment by krystian3w** [comment]
It's just that after this change, the rest changes in the native pop-up is ignored until I return to the correct speed values.

Perhaps there is an error in the developer's console that would make it easier to rewrite the add-on's code to make it resistant to "masochists".

**Comment by Dosx001** [comment]
Can you make a video of this behavior? I don't see how a change in a value in DevTools would affect the extension to ignore the popup settings.

**Comment by krystian3w** [comment]
I will describe in more detail what I do: 

- I open the add-on's native pop-up 
- I select show source from context menu
- I remove `view-source:` from URL to unlock access to standard developer tools
  - And I modify the "1.75" item from the speed selectable list for the value attribute itself (deleting only one 5).
  - The change is saved (works on videos)
  - now on refreshed or opened native pop-up, settijs is a failure that does not allow changing other options until I return to the speeds allowed from the list.

**Comment by Dosx001** [comment]
holy shit lol. That's not how I thought you were doing it. 

For now, just use FireFox's DevTool
https://firefox-source-docs.mozilla.org/devtools-user/

And paste this inside the console
```js
ytutils.speed = 1.7;
ytutils.player.setPlaybackRate(1.7);
```

This should work per tab.
